### ISSUE TITLE
CAN signals

### ISSUE THREAD

**Issue by gabesoares** [sfuphantom/firmware#8]
Write CAN transmission code to send from one launchpad to another through the external MCP2551 transceiver boards. Once this is working do the same for VCU to a launchpad.

**Comment by gabesoares** [comment]
Launchpad to launchpad completed by @mkamalel

**Comment by gabesoares** [comment]
Junaid working on 3 node CAN transmission

**Comment by Junaidk11** [comment]
CAN node 3(Tiva) can talk to individual VCUs (Node 1 & Node 2). However, on the 3 nodes on the same network are not consistent with receiving and transmitting messages.
